# Generated by Django 4.2 on 2023-05-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0002_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("px", models.FloatField()),
                ("py", models.FloatField()),
                ("pz", models.FloatField()),
                ("ox", models.FloatField()),
                ("oy", models.FloatField()),
                ("oz", models.FloatField()),
                ("ow", models.FloatField()),
                (
                    "mmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app0.map"
                    ),
                ),
            ],
        ),
    ]
