# Generated by Django 4.2 on 2023-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0006_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="map", name="x", field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="map", name="y", field=models.FloatField(default=0.0),
        ),
    ]
